// <auto-generated />
namespace MyWebGam.EF.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class ChangeUserForConfirmedEmailaddcolumnEmail : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ChangeUserForConfirmedEmailaddcolumnEmail));
        
        string IMigrationMetadata.Id
        {
            get { return "201702212036575_Change UserForConfirmedEmail(add column Email)"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
